apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::ACCOUNT_ID:role/kubernetes-ci-app-role
      username: ci:deploy-app
      groups:
        - app-deployers

    - rolearn: arn:aws:iam::ACCOUNT_ID:role/kubernetes-ci-monitoring-role
      username: ci:deploy-monitoring
      groups:
        - monitoring-admins
