apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-deploy-binding
  namespace: default
subjects:
  - kind: Group
    name: app-deployers
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: app-deploy-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-admins-binding
subjects:
  - kind: Group
    name: monitoring-admins
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: monitoring-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-helm-binding
  namespace: monitoring
subjects:
  - kind: Group
    name: monitoring-admins
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: monitoring-helm-role
  apiGroup: rbac.authorization.k8s.io
