apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-deploy-binding
  namespace: default
subjects:
  - kind: Group
    name: app-deployers
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: app-deploy-role
  apiGroup: rbac.authorization.k8s.io
